### ISSUE TITLE
Is the data file required by the "generate.py" available?

### ISSUE THREAD

**Issue by justyx404** [larocs/EMG-GAN#1]
Hi,
I am interested in this project and wanted to try it out myself. Although the Ninapro dataset is open to download, they are not in the csv format which the function "load_timeseries" requires.
I wonder if you can provide the following one file so I know what format I need to provide for the script?
"No such file or directory: './data/pd_patient_1_emg.csv'

**Comment by rzanini** [comment]
Hello. Unfortunately the pd_patient_1_emg.csv is based on a private dataset that cannot be shared due to health privacy constrains. But the file schema is the following: TIMESTAMP,FLEXOR_EMG,FLEXOR_EMG_FILTERED,FLEX_EMG_DIFF,EXTENSOR_EMG,EXTENSOR_EMG_FILTERED,EXTENSOR_EMG_DIFF. For the GAN we only use the flexor and extensor EMG filtered signals, so you can adapt the script according to the signals you have.

**Comment by brianrcm** [comment]
> Привет. К сожалению, файл pd_patient_1_emg.csv основан на частном наборе данных, которым нельзя поделиться из-за ограничений конфиденциальности. Но схема файла следующая: TIMESTAMP,FLEXOR_EMG,FLEXOR_EMG_FILTERED,FLEX_EMG_DIFF,EXTENSOR_EMG,EXTENSOR_EMG_FILTERED,EXTENSOR_EMG_DIFF. Для GAN мы используем только отфильтрованные сигналы EMG сгибателей и разгибателей, поэтому вы можете адаптировать сценарий в соответствии с имеющимися у вас сигналами.

Can you write example of file data structures that need to be in the file for correct work?
